version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile 
    ports:
      - 8001:5000
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:12.12
    restart: always
    environment:
      POSTGRES_DATABASE: workshop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: '@hall65536'
    volumes:
      - .dbdata:/var/lib/postgresql/data
    ports:
      - 5438:5432